# Generated by Django 3.1.2 on 2020-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0002_auto_20201106_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
