# Generated by Django 3.1.2 on 2020-11-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0004_auto_20201106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
    ]
