# Generated by Django 3.1.2 on 2020-11-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0005_auto_20201106_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
