# Generated by Django 3.1.2 on 2021-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0006_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
