# Generated by Django 3.1.2 on 2020-11-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201106_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='order_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='', max_length=125),
        ),
    ]
