# Generated by Django 3.1.2 on 2020-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201106_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default='auto_now_add=True'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_message',
            field=models.TextField(),
        ),
    ]
