# Generated by Django 3.1.2 on 2020-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header', models.CharField(max_length=120)),
                ('header_text', models.TextField(max_length=1024)),
                ('about_content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
