# Generated by Django 3.1.2 on 2020-11-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201123_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_content_5',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_content_6',
        ),
    ]
