# Generated by Django 3.1.2 on 2020-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=125)),
                ('course_date', models.DateField()),
                ('course_time', models.TimeField()),
                ('order_message', models.TextField()),
            ],
        ),
    ]
