# Generated by Django 3.1.2 on 2020-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='course_time',
            field=models.TimeField(max_length=20),
        ),
    ]
