# Generated by Django 3.1.2 on 2021-01-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AshVin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ash_vin_header', models.CharField(default='', max_length=120)),
                ('header_text', models.TextField(blank=True, max_length=1024, null=True)),
                ('ash_vin_content', models.TextField(blank=True, null=True)),
                ('ash_vin_content_2', models.TextField(blank=True, null=True)),
                ('ash_vin_content_3', models.TextField(blank=True, null=True)),
                ('ash_vin_content_4', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
