# Generated by Django 3.1.2 on 2021-01-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_header', models.CharField(default='', max_length=120)),
                ('senior_text', models.TextField(blank=True, max_length=1024, null=True)),
                ('senior_content', models.TextField(blank=True, null=True)),
                ('senior_content_2', models.TextField(blank=True, null=True)),
                ('senior_content_3', models.TextField(blank=True, null=True)),
                ('senior_content_4', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
